[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.19"
optimizer = true
optimizer_runs = 200
via_ir = false
bytecode_hash = "none"
cbor_metadata = false
sparse_mode = false
auto_detect_solc = false

[profile.default.fuzz]
runs = 256
max_test_rejects = 65536
seed = '0x3e8'
dictionary_weight = 40
include_storage = true
include_push_bytes = true

[profile.default.invariant]
runs = 256
depth = 15
fail_on_revert = false
call_override = false
dictionary_weight = 80
include_storage = true
include_push_bytes = true

[rpc_endpoints]
coston2 = "https://coston2-api.flare.network/ext/bc/C/rpc"
localhost = "http://127.0.0.1:8545"

[etherscan]
coston2 = { key = "flare", url = "https://coston2-explorer.flare.network/api" }

# See more config options https://github.com/foundry-rs/foundry/tree/master/config